server:
  port: 8082
  tomcat: 
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  application:
    name: azz-merchant-web
  cloud: 
    loadbalancer:
      retry:
        enabled: false #是否开起重试   此开关对ribbon 重试策略生效
  aop:
    proxy-target-class: true
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      

feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: true
    
hystrix: 
  command: 
    default: 
      execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 5000  #熔断时间
ribbon:  
  ReadTimeout: 3000 
  ConnectTimeout: 3000
  OkToRetryOnAllOperations: false  #是否重试
  MaxAutoRetriesNextServer: 0  #是否重试其他服务器
  MaxAutoRetries: 0  #对同一台服务发起重试  
# shiro登录失效时间      
shiro:
  session:
    timeout: 1800000

