server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  application:
    name: azz-platform-web
  aop:
    proxy-target-class: true
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000      
# shiro登录失效时间      
shiro:
  session:
    timeout: 1800000

