server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  messages:
    basename: i18n/Messages
  zipkin:
    enabled: true
    base-url: http://localhost:7777/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  rabbitmq: 
    host: 120.78.162.226
    port: 5672
    username: admin
    password: 123456
  datasource:
    username: root
    password: azz2025
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.162.226:3306/azz_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: false
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml