server:
  port: 7299
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  application:
    name: azz-merchant-management-service
  cloud: 
    loadbalancer:
      retry:
        enabled: false #是否开起重试   此开关对ribbon 重试策略生效
  messages:
    basename: i18n/Messages
  datasource:
    username: root
    password: azz2025
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.162.226:3306/azz_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: true
    
hystrix: 
  command: 
    default: 
      execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 5000  #熔断时间
ribbon:  
  ReadTimeout: 3000 
  ConnectTimeout: 3000
  OkToRetryOnAllOperations: false  #是否重试
  MaxAutoRetriesNextServer: 0  #是否重试其他服务器
  MaxAutoRetries: 0  #对同一台服务发起重试
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml

