server: 
  tomcat: 
    uri-encoding: UTF-8
  port: 8888
  max-http-header-size: 4048576
spring: 
  application:
    name: azz-client-service
  datasource:
    username: root
    password: azz2025
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.162.226:3306/azz_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
      
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml
      